CREATE TABLE nba_stats (
        player VARCHAR NOT NULL,
        pos VARCHAR,
        age int,
        tm VARCHAR,
        g int,
        gs int,
        mp int,
        fg int,
        fga int,
        threepoint int,
        threepoint_att int,
        threepoint_percent float,
        twopoint int,
        twopoint_att int,
        twopoint_percent float,
        orb int,
        drb int,
        trb int,
        ast int,
        stl int,
        blk int,
        tov int,
        pf int,
        pts int,
        PRIMARY KEY (player),
        UNIQUE (player));
    
     CREATE TABLE advanced (
        player VARCHAR NOT NULL,
        pos VARCHAR,
        age	int,
        tm	int,
        g int,
        mp int,
        per int,
        ts_percent int,
        threepoint_attr int,	
        ftr int,
        orb_percent	int,
        drb_percent int,	
        trb_percent int,	
        ast_percent int,	
        stl_percent int,	
        blk_percent int,
        tov_percent int,
        usg_percent int, 	 	
        ows int,	
        dws int,	
        ws int, 	
        ws_per_48 int,	 	
        obpm int,	
        dbpm int,	
        bpm int,	
        vorp int, 
        FOREIGN KEY (player) REFERENCES nba_stats (player),
        PRIMARY KEY (player));
